(cl:defpackage dji_sdk-msg
  (:use )
  (:export
   "<GIMBAL>"
   "GIMBAL"
   "<LANDINGACTIVATION>"
   "LANDINGACTIVATION"
   "<LANDINGDATA>"
   "LANDINGDATA"
   "<MISSIONHOTPOINTTASK>"
   "MISSIONHOTPOINTTASK"
   "<MISSIONWAYPOINT>"
   "MISSIONWAYPOINT"
   "<MISSIONWAYPOINTACTION>"
   "MISSIONWAYPOINTACTION"
   "<MISSIONWAYPOINTTASK>"
   "MISSIONWAYPOINTTASK"
   "<MOBILEDATA>"
   "MOBILEDATA"
   "<WAYPOINT>"
   "WAYPOINT"
   "<WAYPOINTLIST>"
   "WAYPOINTLIST"
   "<LANDINGACTIVATION>"
   "LANDINGACTIVATION"
  ))

